package localization

import "strings"

type Language string

const (
	System Language = "system"
	ZH     Language = "zh-CN"
	EN     Language = "en-US"
)

type Catalog struct {
	language Language
}

func Resolve(configured Language, systemLocale string) Language {
	if configured == ZH || configured == EN {
		return configured
	}
	locale := strings.ToLower(strings.TrimSpace(systemLocale))
	if locale == "zh-cn" || locale == "zh-sg" || strings.HasPrefix(locale, "zh-hans") {
		return ZH
	}
	return EN
}

func New(language Language, systemLocale string) Catalog {
	return Catalog{language: Resolve(language, systemLocale)}
}

func (catalog Catalog) Language() Language { return catalog.language }

func (catalog Catalog) Text(key string) string {
	if catalog.language == ZH {
		if value, ok := zhCN[key]; ok {
			return value
		}
	}
	if value, ok := enUS[key]; ok {
		return value
	}
	return key
}

var enUS = map[string]string{
	"app.title":                        "Genshin Tools",
	"nav.home":                         "Home",
	"nav.game":                         "Game",
	"nav.resources":                    "Resources",
	"nav.server":                       "Server Tools",
	"nav.local":                        "Local Enhancements",
	"nav.capture":                      "Capture & Performance",
	"nav.input":                        "Input Enhancements",
	"nav.injection":                    "Injection",
	"nav.plugins":                      "Plugins",
	"nav.pluginStore":                  "Plugin Store",
	"nav.settings":                     "Settings",
	"nav.home.subtitle":                "Launch status and common actions.",
	"nav.game.subtitle":                "Read-only status, clean launch and launch settings.",
	"nav.resources.subtitle":           "Verify, download and transactionally repair game resources.",
	"nav.server.subtitle":              "Official/Bilibili server switching and advanced conversion.",
	"nav.local.subtitle":               "HDR, startup sound, BetterGI and reversible local operations.",
	"nav.capture.subtitle":             "Game-window screenshots and FPS/CPU/GPU overlay.",
	"nav.input.subtitle":               "Mouse auto-click and keyboard auto-repeat.",
	"nav.injection.subtitle":           "Isolated helper, module preflight and clean-launch fallback.",
	"nav.plugins.subtitle":             "Plugin discovery, configuration, source auditing and updates.",
	"nav.pluginStore.subtitle":         "Explicit HTTPS catalog, filtering and transactional installs.",
	"nav.settings.subtitle":            "Language, appearance, tray, diagnostics and build identity.",
	"status.previousUncleanExit":       "Previous session ended unexpectedly.",
	"status.configRecovered":           "A damaged configuration was quarantined.",
	"common.on":                        "On",
	"common.off":                       "Off",
	"common.enable":                    "Enable",
	"common.disable":                   "Disable",
	"common.unknown":                   "Unknown",
	"home.ready":                       "Launcher services are ready",
	"home.summary":                     "Single instance · notification area · per-monitor DPI · atomic configuration · safe shutdown",
	"home.scope":                       "Focused launcher only; account, HoYoLAB/BBS, toolbox and browser features are not included.",
	"input.toggle":                     "Input enhancement: %s    Click to %s",
	"input.mode.keyboard":              "Keyboard repeat",
	"input.mode.mouseLeft":             "Left auto-click",
	"input.mode.mouseRight":            "Right auto-click",
	"input.key.trigger":                "Trigger key",
	"input.key.output":                 "Output key",
	"input.key.stop":                   "Global stop key",
	"input.mouseTrigger":               "Trigger: hold the corresponding physical mouse button",
	"input.interval":                   "−       Interval %d ms       +",
	"input.error":                      "Error: %s",
	"input.outputCount":                "Emitted %d complete down/up pairs; input enhancement starts disabled after restart",
	"input.record.pending":             "%s: press a new key…",
	"input.record.ready":               "%s: %s    Click to record",
	"input.state.disabled":             "Disabled",
	"input.state.armed":                "Armed",
	"input.state.running":              "Running",
	"input.state.stopping":             "Stopping",
	"input.state.fault":                "Fault",
	"input.state.unknown":              "Unknown",
	"game.launch.clean":                "Launch game cleanly",
	"game.launch.starting":             "Starting…",
	"game.launch.running":              "Game is running (session PID %d)",
	"game.windowMode":                  "Window mode: %s    Click to change",
	"game.window.default":              "Game default",
	"game.window.fullscreen":           "Fullscreen",
	"game.window.windowed":             "Windowed",
	"game.window.borderless":           "Borderless",
	"game.resolution":                  "Resolution: %s    Click to change preset",
	"game.monitor.default":             "Default",
	"game.monitor.number":              "Monitor %d",
	"game.target":                      "Target: %s",
	"game.after":                       "After launch: %s",
	"game.post.keep":                   "Keep launcher",
	"game.post.minimize":               "Minimize to notification area",
	"game.post.exit":                   "Exit after launch",
	"game.action.scan":                 "Rescan / cancel",
	"game.action.select":               "Select game EXE",
	"game.action.shortcut":             "Create desktop shortcut",
	"game.error.launch":                "Launch error: %s",
	"game.error.process":               "Game process error: %s",
	"game.exited":                      "Game exited with code %d; it can be launched again",
	"game.path":                        "Path: %s",
	"game.identity":                    "%s    Version %s    %s",
	"game.files":                       "%s · %d files · skipped %d · %s",
	"game.running.none":                "Not running",
	"game.running.verified":            "Running PID %d (path verified)",
	"game.running.possible":            "Possibly running PID %d (name match only)",
	"game.server.official":             "Mainland China official",
	"game.server.bilibili":             "Mainland China Bilibili",
	"game.server.global":               "Global",
	"game.server.unknown":              "Unknown",
	"game.status.selectFirst":          "Select and finish scanning a game installation first",
	"game.status.scanCanceled":         "Scan canceled",
	"game.status.selectGame":           "Select a game first",
	"game.status.shortcutFailed":       "Shortcut creation failed: %s",
	"game.status.shortcutCreated":      "Created: %s",
	"game.status.scanning":             "Scanning local game installations read-only…",
	"game.status.validating":           "Validating candidate paths…",
	"game.status.multiple":             "Found %d installations; select the game EXE manually",
	"game.status.notFound":             "No valid game installation was found",
	"game.status.calculating":          "Calculating directory size (cancelable)…",
	"game.status.complete":             "Read-only scan complete",
	"game.status.savePathFailed":       "Failed to save game path: %s",
	"game.shortcut.name":               "Genshin Impact - Genshin Tools",
	"resource.check":                   "Check online resources and build repair plan",
	"resource.cancel":                  "Cancel current resource task",
	"resource.voice":                   "Voice pack: %s    Click to change",
	"resource.branch":                  "Resource branch: %s    Click to change",
	"resource.branch.current":          "Current release",
	"resource.branch.preload":          "Pre-download release (when officially available)",
	"resource.apply.needPlan":          "Download and repair (build a plan first)",
	"resource.apply.count":             "Download and repair %d files",
	"resource.apply.confirm":           "Click again to confirm; original files are backed up transactionally",
	"resource.onlineVersion":           "Online version: %s",
	"resource.planSummary":             "Manifest %d files · process %d · download %s",
	"resource.progress":                "%d/%d files · %s/%s · %s/s · remaining %s",
	"resource.eta.calculating":         "calculating",
	"resource.safety":                  "Safety boundary: downloads only enter data/staging; a short commit starts after complete verification.",
	"resource.status.ready":            "Check online resources first to build a read-only repair plan",
	"resource.status.canceling":        "Canceling resource task…",
	"resource.status.voiceChanged":     "Voice pack changed; check resources again",
	"resource.status.branchChanged":    "Resource branch changed; check again",
	"resource.status.noChanges":        "All current files passed verification; no repair is needed",
	"resource.status.confirm":          "Click again to confirm download and transactional replacement",
	"resource.status.reading":          "Reading the official resource catalog…",
	"resource.status.manifest":         "Verifying online manifest…",
	"resource.status.planning":         "Building a read-only repair plan file by file…",
	"resource.status.canceled":         "Resource check canceled",
	"resource.status.failed":           "Resource check failed; game files were not modified",
	"resource.status.planComplete":     "Plan complete: %d files need download or repair",
	"resource.status.preparing":        "Preparing isolated transaction…",
	"resource.status.downloading":      "Downloading to data/staging; game files remain unchanged",
	"resource.status.preloadFailed":    "Could not save pre-download; game files were not modified",
	"resource.status.preloaded":        "Pre-download fully verified in data/staging; game files were not modified",
	"resource.status.committing":       "Download fully verified; committing transaction…",
	"resource.status.taskCanceled":     "Resource task canceled; game files were not modified",
	"resource.status.txFailed":         "Resource transaction failed; original files were preserved or restored",
	"resource.status.complete":         "Resource transaction complete; all target files were verified again",
	"resource.error.needPlan":          "Build a repair plan first",
	"resource.error.gameRunning":       "Resources cannot be replaced while the game is running; exit the game first",
	"resource.error.selectGame":        "Select a game directory on the Game page first",
	"resource.error.noPreload":         "The official pre-download branch is not currently available",
	"server.mode":                      "Method: %s    Click to change",
	"server.mode.quick":                "Official/Bilibili quick switch",
	"server.mode.advanced":             "Mainland China/Global advanced conversion",
	"server.target":                    "Target: %s    Click to change",
	"server.target.official":           "Mainland China official",
	"server.target.bilibili":           "Mainland China Bilibili",
	"server.target.global":             "Global",
	"server.plan":                      "Build change preview",
	"server.cancel":                    "Cancel current server task",
	"server.commit.inProgress":         "Transactional commit in progress (cannot be canceled safely)",
	"server.commit.needPlan":           "Commit switch (build a preview first)",
	"server.commit.count":              "Commit %d changes",
	"server.commit.confirm":            "Click again to confirm transactional commit",
	"server.planSummary":               "Install/replace %d · rename %d · reversible delete %d · download %s",
	"server.advancedInfo":              "Advanced conversion verifies and downloads target differences before committing directory/EXE renames, replacements and configuration together.",
	"server.rollbackInfo":              "The complete Plugins directory is never cleared; any failure restores the original server layout from the reverse journal.",
	"server.status.ready":              "Build a server change preview first; the game directory will not be modified immediately",
	"server.status.canceling":          "Canceling server task…",
	"server.status.modeChanged":        "Switch method changed; rebuild the change preview",
	"server.status.targetChanged":      "Target changed; rebuild the change preview",
	"server.status.confirm":            "Click again to confirm; every replacement and deletion has a transactional backup",
	"server.status.readingQuick":       "Reading official channel SDK metadata and preparing isolated files…",
	"server.status.readingAdvanced":    "Reading target-region Sophon metadata and preparing the full difference; download may take some time…",
	"server.status.previewCanceled":    "Server preview canceled; game files were not modified",
	"server.status.previewFailed":      "Server preview failed; game files were not modified",
	"server.status.previewComplete":    "Preview complete: %d planned changes; the game directory remains unchanged until confirmation",
	"server.status.committing":         "Committing server transaction; failures roll back in reverse order…",
	"server.status.commitFailed":       "Server switch failed; original configuration and SDK were restored",
	"server.status.complete":           "Server switch complete",
	"server.error.needPreview":         "Build a server change preview first",
	"server.error.gameRunning":         "The server cannot be switched while the game is running",
	"server.error.selectGame":          "Select a valid game directory on the Game page first",
	"server.error.quickMainlandOnly":   "Official/Bilibili quick switch only supports a recognized Mainland China YuanShen.exe installation",
	"local.hdrState":                   "HDR forced state: %s    Click to change target",
	"local.brightness":                 "Brightness: peak %d · scene %d · UI %d    Click to change safe preset",
	"local.hdrApply":                   "Apply HDR (back up first, then write)",
	"local.hdrRestore":                 "Restore the previous original HDR registry values",
	"local.sound.select":               "Select and preview WAV: %s",
	"local.sound.enabled":              "Startup sound: %s",
	"local.betterGI.enabled":           "BetterGI protocol integration: %s",
	"local.betterGI.delay":             "BetterGI launch delay: %.1f seconds    Click to change",
	"local.betterGI.audit":             "Audit and test BetterGI URL Scheme (never terminates processes by name)",
	"local.safety":                     "Failures on this page never block a clean game launch",
	"local.sound.prompt":               "Select startup WAV sound",
	"local.status.saveFailed":          "Failed to save local enhancement settings: %s",
	"local.status.hdrTargetChanged":    "HDR target state changed; click Apply HDR to write it",
	"local.status.hdrPresetChanged":    "HDR brightness preset changed; registry has not been modified",
	"local.status.hdrMainlandOnly":     "HDR registry adaptation only supports a recognized Mainland China game directory",
	"local.status.hdrApplyFailed":      "Failed to apply HDR; old values were preserved or restored: %s",
	"local.status.hdrApplied":          "HDR applied; original registry values were backed up",
	"local.status.hdrRestoreFailed":    "Failed to restore HDR backup: %s",
	"local.status.hdrRestored":         "Original HDR registry values restored",
	"local.status.soundSelectFailed":   "Failed to select WAV: %s",
	"local.status.soundPreviewFailed":  "Failed to preview WAV: %s",
	"local.status.soundSelected":       "Startup sound selected and previewed",
	"local.status.soundEnabled":        "Startup sound: %s",
	"local.status.betterGIEnabled":     "BetterGI integration: %s",
	"local.status.betterGIDelay":       "BetterGI delay updated",
	"local.status.betterGIAuditFailed": "BetterGI audit failed: %s",
	"local.status.betterGINotFound":    "BetterGI URL Scheme was not found; clean launch is unaffected",
	"local.status.betterGIStartFailed": "BetterGI test launch failed: %s",
	"local.status.betterGIStarted":     "Launch request sent to the verified BetterGI URL Scheme",
	"media.capture":                    "Game-window capture: %s    Click to change",
	"media.hotkey":                     "Global capture key: %s    Click to change safe preset",
	"media.captureNow":                 "Capture the verified game window now",
	"media.saveDir":                    "Save directory: %s",
	"media.overlay":                    "Performance overlay: %s    Click to change",
	"media.metrics":                    "Displayed metrics: %s    Click to change combination",
	"media.offset":                     "Overlay offset: X %d · Y %d    Click to change preset",
	"media.realtime":                   "Live: FPS %s · CPU %s · GPU %s",
	"media.folder.prompt":              "Select screenshot save directory",
	"media.status.captureDisabled":     "Screenshot capture is disabled",
	"media.status.captureFailed":       "Screenshot failed: %s",
	"media.status.captureSaved":        "Screenshot saved: %s",
	"media.status.hotkeyFailed":        "Could not register screenshot hotkey: %s",
	"media.status.captureWaiting":      "Screenshot capture enabled; waiting for a verified game window",
	"media.status.captureEnabled":      "Screenshot capture enabled: %s",
	"media.status.captureStopped":      "Screenshot capture disabled",
	"media.status.hotkeyChangeFailed":  "Could not change screenshot key: %s",
	"media.status.hotkeyChanged":       "Screenshot key changed to %s",
	"media.status.requestQueued":       "Screenshot request entered the bounded queue…",
	"media.status.requestRejected":     "Could not capture: enable capture and start a verified game window",
	"media.status.folderFailed":        "Could not select screenshot directory: %s",
	"media.status.folderInvalid":       "Screenshot directory is invalid: %s",
	"media.status.folderSet":           "Screenshot directory set: %s",
	"media.status.saveFailed":          "Failed to save capture and overlay settings: %s",
	"media.status.overlayDisabled":     "Performance overlay is disabled",
	"media.status.overlayFailed":       "Overlay failed to start: %s",
	"media.status.overlayRunning":      "Overlay running: PID %d",
	"media.status.overlayStopped":      "Performance overlay stopped",
	"media.status.overlayWaiting":      "Overlay enabled; waiting for a verified game window",
	"media.status.overlayReconciling":  "Coordinating overlay lifecycle…",
	"media.error.hotkeyConflict":       "Screenshot key conflicts with an input-enhancement physical key",
	"settings.subtitle":                "Language, appearance, tray, window, diagnostics and version information.",
	"settings.language":                "Language",
	"settings.language.system":         "System default",
	"settings.language.zh":             "Simplified Chinese",
	"settings.language.en":             "English",
	"settings.theme":                   "Theme",
	"settings.theme.dark":              "Dark",
	"settings.theme.system":            "Follow Windows",
	"settings.tray":                    "Minimize to notification area",
	"settings.rememberWindow":          "Remember window position and size",
	"settings.minimumSize":             "Enforce safe minimum window size",
	"settings.priority":                "Process priority",
	"settings.priority.below":          "Below normal",
	"settings.priority.normal":         "Normal",
	"settings.priority.above":          "Above normal",
	"settings.cpuWarning":              "Warn when launcher CPU usage stays high",
	"settings.cpuWarning.title":        "High launcher CPU usage",
	"settings.cpuWarning.message":      "Launcher CPU usage remained above the configured threshold.",
	"settings.about":                   "About and build identity",
	"settings.diagnostics":             "Export privacy-filtered diagnostics",
	"settings.upstream":                "Audited upstream commit",
	"settings.scope":                   "Scope policy",
	"settings.status.saved":            "Settings saved",
	"settings.status.ready":            "Settings are ready",
	"settings.status.saveFailed":       "Failed to save settings: ",
	"settings.status.exporting":        "Exporting diagnostics…",
	"settings.status.exported":         "Diagnostics exported: ",
	"settings.status.exportFailed":     "Failed to export diagnostics: ",
	"settings.diagnostics.prompt":      "Select diagnostic export folder",
}

var zhCN = map[string]string{
	"app.title":                        "Genshin Tools",
	"nav.home":                         "首页",
	"nav.game":                         "游戏管理",
	"nav.resources":                    "资源管理",
	"nav.server":                       "区服工具",
	"nav.local":                        "本地增强",
	"nav.capture":                      "截图与性能",
	"nav.input":                        "输入增强",
	"nav.injection":                    "注入适配",
	"nav.plugins":                      "插件",
	"nav.pluginStore":                  "插件商店",
	"nav.settings":                     "设置",
	"nav.home.subtitle":                "启动状态与常用操作。",
	"nav.game.subtitle":                "只读状态、纯净启动和启动设置。",
	"nav.resources.subtitle":           "检查、下载并事务修复游戏资源。",
	"nav.server.subtitle":              "官服/B服切换与高级转换。",
	"nav.local.subtitle":               "HDR、启动声音、BetterGI 与可回滚本地操作。",
	"nav.capture.subtitle":             "游戏窗口截图与 FPS/CPU/GPU 覆盖层。",
	"nav.input.subtitle":               "鼠标连点与键盘连按。",
	"nav.injection.subtitle":           "独立 helper、模块预检和纯净启动回退。",
	"nav.plugins.subtitle":             "插件发现、配置、来源审计和更新。",
	"nav.pluginStore.subtitle":         "显式 HTTPS 目录、筛选和事务安装。",
	"nav.settings.subtitle":            "语言、外观、托盘、诊断与构建身份。",
	"status.previousUncleanExit":       "已检测到上次异常退出。",
	"status.configRecovered":           "已隔离损坏配置。",
	"common.on":                        "开启",
	"common.off":                       "关闭",
	"common.enable":                    "启用",
	"common.disable":                   "禁用",
	"common.unknown":                   "未知",
	"home.ready":                       "启动器服务已就绪",
	"home.summary":                     "单实例 · 通知区域 · 每显示器 DPI · 原子配置 · 安全退出",
	"home.scope":                       "仅保留启动器功能；不包含账号、米游社/BBS、工具箱和浏览器功能。",
	"input.toggle":                     "输入增强：%s    单击%s",
	"input.mode.keyboard":              "键盘连按",
	"input.mode.mouseLeft":             "左键连点",
	"input.mode.mouseRight":            "右键连点",
	"input.key.trigger":                "触发键",
	"input.key.output":                 "输出键",
	"input.key.stop":                   "全局停止键",
	"input.mouseTrigger":               "触发方式：按住对应物理鼠标键",
	"input.interval":                   "−       间隔 %d ms       +",
	"input.error":                      "错误：%s",
	"input.outputCount":                "已输出 %d 组完整 down/up；重启后默认保持禁用",
	"input.record.pending":             "%s：请按下新按键…",
	"input.record.ready":               "%s：%s    单击录制",
	"input.state.disabled":             "已禁用",
	"input.state.armed":                "待触发",
	"input.state.running":              "运行中",
	"input.state.stopping":             "停止中",
	"input.state.fault":                "故障",
	"input.state.unknown":              "未知",
	"game.launch.clean":                "纯净启动游戏",
	"game.launch.starting":             "正在启动…",
	"game.launch.running":              "游戏运行中（本次 PID %d）",
	"game.windowMode":                  "窗口模式：%s    单击切换",
	"game.window.default":              "游戏默认",
	"game.window.fullscreen":           "全屏",
	"game.window.windowed":             "窗口",
	"game.window.borderless":           "无边框",
	"game.resolution":                  "分辨率：%s    单击切换预设",
	"game.monitor.default":             "默认",
	"game.monitor.number":              "显示器 %d",
	"game.target":                      "目标：%s",
	"game.after":                       "之后：%s",
	"game.post.keep":                   "保持启动器",
	"game.post.minimize":               "最小化到托盘",
	"game.post.exit":                   "启动后退出",
	"game.action.scan":                 "重新扫描/取消",
	"game.action.select":               "选择游戏 EXE",
	"game.action.shortcut":             "创建桌面快捷方式",
	"game.error.launch":                "启动错误：%s",
	"game.error.process":               "游戏进程错误：%s",
	"game.exited":                      "游戏已退出，代码 %d；启动器可再次启动",
	"game.path":                        "路径：%s",
	"game.identity":                    "%s    版本 %s    %s",
	"game.files":                       "%s · %d 文件 · 跳过 %d · %s",
	"game.running.none":                "未运行",
	"game.running.verified":            "运行中 PID %d（路径已核验）",
	"game.running.possible":            "可能运行 PID %d（仅名称匹配）",
	"game.server.official":             "国服官服",
	"game.server.bilibili":             "国服 B 服",
	"game.server.global":               "国际服",
	"game.server.unknown":              "未知",
	"game.status.selectFirst":          "请先选择并完成游戏扫描",
	"game.status.scanCanceled":         "扫描已取消",
	"game.status.selectGame":           "请先选择游戏",
	"game.status.shortcutFailed":       "快捷方式失败：%s",
	"game.status.shortcutCreated":      "已创建：%s",
	"game.status.scanning":             "正在只读扫描本机游戏…",
	"game.status.validating":           "正在验证候选路径…",
	"game.status.multiple":             "发现 %d 个安装，请手动选择游戏 EXE",
	"game.status.notFound":             "未找到有效游戏安装",
	"game.status.calculating":          "正在计算目录大小（可取消）…",
	"game.status.complete":             "只读扫描完成",
	"game.status.savePathFailed":       "保存游戏路径：%s",
	"game.shortcut.name":               "原神 - Genshin Tools",
	"resource.check":                   "检查在线资源并生成修复计划",
	"resource.cancel":                  "取消当前资源任务",
	"resource.voice":                   "语音包：%s    单击切换",
	"resource.branch":                  "资源分支：%s    单击切换",
	"resource.branch.current":          "当前正式版本",
	"resource.branch.preload":          "预下载版本（仅官方开放时可用）",
	"resource.apply.needPlan":          "下载并修复（需要先生成计划）",
	"resource.apply.count":             "下载并修复 %d 个文件",
	"resource.apply.confirm":           "再次单击确认执行；原文件将在事务中备份",
	"resource.onlineVersion":           "在线版本：%s",
	"resource.planSummary":             "清单 %d 个文件 · 需处理 %d 个 · 下载量 %s",
	"resource.progress":                "%d/%d 文件 · %s/%s · %s/s · 剩余 %s",
	"resource.eta.calculating":         "计算中",
	"resource.safety":                  "安全边界：下载仅写入 data/staging；完整校验后才进入短暂提交阶段。",
	"resource.status.ready":            "先检查在线资源并生成只读修复计划",
	"resource.status.canceling":        "正在取消资源任务…",
	"resource.status.voiceChanged":     "语音包已切换，请重新检查资源",
	"resource.status.branchChanged":    "资源分支已切换，请重新检查",
	"resource.status.noChanges":        "当前文件均已通过校验，无需修复",
	"resource.status.confirm":          "再次单击以确认下载并事务替换列出的文件",
	"resource.status.reading":          "正在读取官方资源目录…",
	"resource.status.manifest":         "正在校验在线 manifest…",
	"resource.status.planning":         "正在逐文件生成只读修复计划…",
	"resource.status.canceled":         "资源检查已取消",
	"resource.status.failed":           "资源检查失败，未修改游戏文件",
	"resource.status.planComplete":     "计划完成：%d 个文件需下载或修复",
	"resource.status.preparing":        "正在准备隔离事务…",
	"resource.status.downloading":      "正在下载到 data/staging；正式文件保持不变",
	"resource.status.preloadFailed":    "预下载保存失败；正式文件未修改",
	"resource.status.preloaded":        "预下载已完整校验并保存在 data/staging；正式文件未修改",
	"resource.status.committing":       "下载已完整校验，正在提交事务…",
	"resource.status.taskCanceled":     "资源任务已取消；正式文件未修改",
	"resource.status.txFailed":         "资源事务失败；已保留或恢复原文件",
	"resource.status.complete":         "资源事务完成，全部目标文件已再次校验",
	"resource.error.needPlan":          "请先生成修复计划",
	"resource.error.gameRunning":       "游戏运行时不能替换资源，请先退出游戏",
	"resource.error.selectGame":        "请先在游戏管理页选择游戏目录",
	"resource.error.noPreload":         "官方当前没有开放预下载分支",
	"server.mode":                      "方式：%s    单击切换",
	"server.mode.quick":                "官服/B服快速切换",
	"server.mode.advanced":             "国服/国际服高级转换",
	"server.target":                    "目标：%s    单击切换",
	"server.target.official":           "国服官服",
	"server.target.bilibili":           "国服 B 服",
	"server.target.global":             "国际服",
	"server.plan":                      "生成变更预览",
	"server.cancel":                    "取消当前区服任务",
	"server.commit.inProgress":         "区服事务提交中（不能安全取消）",
	"server.commit.needPlan":           "提交切换（需要先生成预览）",
	"server.commit.count":              "提交 %d 项变更",
	"server.commit.confirm":            "再次单击确认事务提交",
	"server.planSummary":               "安装/替换 %d · 改名 %d · 可回滚删除 %d · 下载 %s",
	"server.advancedInfo":              "高级转换会先校验并下载目标差异，再统一提交目录/EXE 改名、替换和配置。",
	"server.rollbackInfo":              "不会清空整个 Plugins；任一步失败均按反向日志恢复原区服布局。",
	"server.status.ready":              "先生成区服变更预览；不会直接修改游戏目录",
	"server.status.canceling":          "正在取消区服任务…",
	"server.status.modeChanged":        "切换方式已更改，请重新生成变更预览",
	"server.status.targetChanged":      "目标已切换，请重新生成变更预览",
	"server.status.confirm":            "再次单击确认提交；所有替换和删除均有事务备份",
	"server.status.readingQuick":       "正在读取官方渠道 SDK 清单并准备隔离文件…",
	"server.status.readingAdvanced":    "正在读取目标区服 Sophon 清单并准备完整差异；可能需要较长下载…",
	"server.status.previewCanceled":    "区服预览已取消；游戏文件未修改",
	"server.status.previewFailed":      "区服预览失败；游戏文件未修改",
	"server.status.previewComplete":    "预览完成：%d 项计划，确认前不会修改游戏目录",
	"server.status.committing":         "正在提交区服事务；失败将自动逆序回滚…",
	"server.status.commitFailed":       "区服切换失败；原配置和 SDK 已恢复",
	"server.status.complete":           "区服切换完成",
	"server.error.needPreview":         "请先生成区服变更预览",
	"server.error.gameRunning":         "游戏运行时不能切换区服",
	"server.error.selectGame":          "请先在游戏管理页选择有效游戏目录",
	"server.error.quickMainlandOnly":   "官服/B服快速切换仅适用于已识别的国服 YuanShen.exe",
	"local.hdrState":                   "HDR 强制状态：%s    单击切换目标",
	"local.brightness":                 "亮度：峰值 %d · 场景 %d · UI %d    单击切换安全预设",
	"local.hdrApply":                   "应用 HDR（先备份，再写入）",
	"local.hdrRestore":                 "恢复上一次 HDR 原始注册表值",
	"local.sound.select":               "选择并试听 WAV：%s",
	"local.sound.enabled":              "启动声音：%s",
	"local.betterGI.enabled":           "BetterGI 协议联动：%s",
	"local.betterGI.delay":             "BetterGI 启动延迟：%.1f 秒    单击切换",
	"local.betterGI.audit":             "审计并测试 BetterGI URL Scheme（不会按名称结束进程）",
	"local.safety":                     "本页操作失败不会阻止纯净游戏启动",
	"local.sound.prompt":               "选择启动声音 WAV",
	"local.status.saveFailed":          "保存本地增强设置失败：%s",
	"local.status.hdrTargetChanged":    "HDR 目标状态已更改；单击“应用 HDR”后写入",
	"local.status.hdrPresetChanged":    "HDR 亮度预设已更改，尚未写入注册表",
	"local.status.hdrMainlandOnly":     "HDR 注册表适配仅用于已识别的国服目录",
	"local.status.hdrApplyFailed":      "应用 HDR 失败，旧值已保留或恢复：%s",
	"local.status.hdrApplied":          "HDR 已应用；原始注册表值已备份",
	"local.status.hdrRestoreFailed":    "恢复 HDR 备份失败：%s",
	"local.status.hdrRestored":         "HDR 原始注册表值已恢复",
	"local.status.soundSelectFailed":   "选择 WAV 失败：%s",
	"local.status.soundPreviewFailed":  "WAV 试听失败：%s",
	"local.status.soundSelected":       "启动声音已选择并试听",
	"local.status.soundEnabled":        "启动声音：%s",
	"local.status.betterGIEnabled":     "BetterGI 联动：%s",
	"local.status.betterGIDelay":       "BetterGI 延迟已更新",
	"local.status.betterGIAuditFailed": "BetterGI 审计失败：%s",
	"local.status.betterGINotFound":    "未发现 BetterGI URL Scheme；不会影响纯净启动",
	"local.status.betterGIStartFailed": "BetterGI 测试启动失败：%s",
	"local.status.betterGIStarted":     "已向核验后的 BetterGI URL Scheme 发送启动请求",
	"media.capture":                    "游戏窗口截图：%s    单击切换",
	"media.hotkey":                     "全局截图键：%s    单击切换安全预设",
	"media.captureNow":                 "立即截取已核验游戏窗口",
	"media.saveDir":                    "保存目录：%s",
	"media.overlay":                    "性能覆盖层：%s    单击切换",
	"media.metrics":                    "显示指标：%s    单击切换组合",
	"media.offset":                     "覆盖层偏移：X %d · Y %d    单击切换预设",
	"media.realtime":                   "实时：FPS %s · CPU %s · GPU %s",
	"media.folder.prompt":              "选择截图保存目录",
	"media.status.captureDisabled":     "截图功能未启用",
	"media.status.captureFailed":       "截图失败：%s",
	"media.status.captureSaved":        "截图已保存：%s",
	"media.status.hotkeyFailed":        "截图快捷键注册失败：%s",
	"media.status.captureWaiting":      "截图已启用，等待已核验游戏窗口",
	"media.status.captureEnabled":      "截图已启用：%s",
	"media.status.captureStopped":      "截图功能已停用",
	"media.status.hotkeyChangeFailed":  "切换截图键失败：%s",
	"media.status.hotkeyChanged":       "截图键已改为 %s",
	"media.status.requestQueued":       "截图请求已进入有界队列…",
	"media.status.requestRejected":     "无法截图：请启用截图并启动已核验的游戏窗口",
	"media.status.folderFailed":        "选择截图目录失败：%s",
	"media.status.folderInvalid":       "截图目录无效：%s",
	"media.status.folderSet":           "截图目录已设置：%s",
	"media.status.saveFailed":          "保存截图与覆盖层设置失败：%s",
	"media.status.overlayDisabled":     "性能覆盖层未启用",
	"media.status.overlayFailed":       "覆盖层启动失败：%s",
	"media.status.overlayRunning":      "覆盖层运行中：PID %d",
	"media.status.overlayStopped":      "性能覆盖层已停止",
	"media.status.overlayWaiting":      "覆盖层已启用，等待已核验游戏窗口",
	"media.status.overlayReconciling":  "正在协调覆盖层生命周期…",
	"media.error.hotkeyConflict":       "截图键与输入增强物理键冲突",
	"settings.subtitle":                "语言、外观、托盘、窗口、诊断与版本信息。",
	"settings.language":                "语言",
	"settings.language.system":         "跟随系统",
	"settings.language.zh":             "简体中文",
	"settings.language.en":             "English",
	"settings.theme":                   "主题",
	"settings.theme.dark":              "暗色",
	"settings.theme.system":            "跟随 Windows",
	"settings.tray":                    "最小化到通知区域",
	"settings.rememberWindow":          "记住窗口位置和尺寸",
	"settings.minimumSize":             "启用安全最小窗口尺寸",
	"settings.priority":                "程序进程优先级",
	"settings.priority.below":          "低于正常",
	"settings.priority.normal":         "正常",
	"settings.priority.above":          "高于正常",
	"settings.cpuWarning":              "程序持续高 CPU 占用时提醒",
	"settings.cpuWarning.title":        "程序 CPU 占用持续偏高",
	"settings.cpuWarning.message":      "程序 CPU 占用已持续超过配置阈值。",
	"settings.about":                   "关于与构建身份",
	"settings.diagnostics":             "导出经过隐私过滤的诊断",
	"settings.upstream":                "已审计上游提交",
	"settings.scope":                   "范围策略",
	"settings.status.saved":            "设置已保存",
	"settings.status.ready":            "设置已就绪",
	"settings.status.saveFailed":       "保存设置失败：",
	"settings.status.exporting":        "正在导出诊断…",
	"settings.status.exported":         "诊断已导出：",
	"settings.status.exportFailed":     "导出诊断失败：",
	"settings.diagnostics.prompt":      "选择诊断导出目录",
}
