package localization

import "strings"

type Language string

const (
	System Language = "system"
	ZH     Language = "zh-CN"
	EN     Language = "en-US"
)

type Catalog struct {
	language Language
}

func Resolve(configured Language, systemLocale string) Language {
	if configured == ZH || configured == EN {
		return configured
	}
	locale := strings.ToLower(strings.TrimSpace(systemLocale))
	if locale == "zh-cn" || locale == "zh-sg" || strings.HasPrefix(locale, "zh-hans") {
		return ZH
	}
	return EN
}

func New(language Language, systemLocale string) Catalog {
	return Catalog{language: Resolve(language, systemLocale)}
}

func (catalog Catalog) Language() Language { return catalog.language }

func (catalog Catalog) Text(key string) string {
	if catalog.language == ZH {
		if value, ok := zhCN[key]; ok {
			return value
		}
	}
	if value, ok := enUS[key]; ok {
		return value
	}
	return key
}

var enUS = map[string]string{
	"app.title":                           "Genshin Tools",
	"nav.home":                            "Home",
	"nav.game":                            "Game",
	"nav.resources":                       "Resources",
	"nav.server":                          "Server Tools",
	"nav.local":                           "Local Enhancements",
	"nav.capture":                         "Capture & Performance",
	"nav.input":                           "Input Enhancements",
	"nav.injection":                       "Injection",
	"nav.plugins":                         "Plugins",
	"nav.pluginStore":                     "Plugin Store",
	"nav.settings":                        "Settings",
	"nav.home.subtitle":                   "Launch status and common actions.",
	"nav.game.subtitle":                   "Read-only status, clean launch and launch settings.",
	"nav.resources.subtitle":              "Verify, download and transactionally repair game resources.",
	"nav.server.subtitle":                 "Official/Bilibili server switching and advanced conversion.",
	"nav.local.subtitle":                  "HDR, startup sound, BetterGI and reversible local operations.",
	"nav.capture.subtitle":                "Game-window screenshots and FPS/CPU/GPU overlay.",
	"nav.input.subtitle":                  "Mouse auto-click and keyboard auto-repeat.",
	"nav.injection.subtitle":              "Isolated helper, module preflight and clean-launch fallback.",
	"nav.plugins.subtitle":                "Plugin discovery, configuration, source auditing and updates.",
	"nav.pluginStore.subtitle":            "FufuLauncher store, filtering and official verification flow.",
	"nav.settings.subtitle":               "Language, appearance, tray, diagnostics and build identity.",
	"status.previousUncleanExit":          "Previous session ended unexpectedly.",
	"status.configRecovered":              "A damaged configuration was quarantined.",
	"common.on":                           "On",
	"common.off":                          "Off",
	"common.enable":                       "Enable",
	"common.disable":                      "Disable",
	"common.unknown":                      "Unknown",
	"common.label":                        "%s: %s",
	"home.ready":                          "Launcher services are ready",
	"home.summary":                        "Single instance · notification area · per-monitor DPI · atomic configuration · safe shutdown",
	"home.scope":                          "Focused launcher only; account, HoYoLAB/BBS, toolbox and browser features are not included.",
	"input.toggle":                        "Input enhancement: %s    Click to %s",
	"input.mode.keyboard":                 "Keyboard repeat",
	"input.mode.mouseLeft":                "Left auto-click",
	"input.mode.mouseRight":               "Right auto-click",
	"input.key.trigger":                   "Trigger key",
	"input.key.output":                    "Output key",
	"input.key.stop":                      "Global stop key",
	"input.mouseTrigger":                  "Trigger: hold the corresponding physical mouse button",
	"input.interval":                      "−       Interval %d ms       +",
	"input.error":                         "Error: %s",
	"input.outputCount":                   "Emitted %d complete down/up pairs; input enhancement starts disabled after restart",
	"input.record.pending":                "%s: press a new key…",
	"input.record.ready":                  "%s: %s    Click to record",
	"input.state.disabled":                "Disabled",
	"input.state.armed":                   "Armed",
	"input.state.running":                 "Running",
	"input.state.stopping":                "Stopping",
	"input.state.fault":                   "Fault",
	"input.state.unknown":                 "Unknown",
	"input.error.captureConflict":         "This physical key is already used by the screenshot hotkey; modifier differences may still trigger the input stop logic",
	"game.launch.clean":                   "Launch game cleanly",
	"game.launch.starting":                "Starting…",
	"game.launch.running":                 "Game is running (session PID %d)",
	"game.windowMode":                     "Window mode: %s    Click to change",
	"game.window.default":                 "Game default",
	"game.window.fullscreen":              "Fullscreen",
	"game.window.windowed":                "Windowed",
	"game.window.borderless":              "Borderless",
	"game.resolution":                     "Resolution: %s    Click to change preset",
	"game.monitor.default":                "Default",
	"game.monitor.number":                 "Monitor %d",
	"game.target":                         "Target: %s",
	"game.after":                          "After launch: %s",
	"game.post.keep":                      "Keep launcher",
	"game.post.minimize":                  "Minimize to notification area",
	"game.post.exit":                      "Exit after launch",
	"game.action.scan":                    "Rescan / cancel",
	"game.action.select":                  "Select game EXE",
	"game.action.shortcut":                "Create desktop shortcut",
	"game.error.launch":                   "Launch error: %s",
	"game.error.process":                  "Game process error: %s",
	"game.exited":                         "Game exited with code %d; it can be launched again",
	"game.path":                           "Path: %s",
	"game.identity":                       "%s    Version %s    %s",
	"game.files":                          "%s · %d files · skipped %d · %s",
	"game.running.none":                   "Not running",
	"game.running.verified":               "Running PID %d (path verified)",
	"game.running.possible":               "Possibly running PID %d (name match only)",
	"game.server.official":                "Mainland China official",
	"game.server.bilibili":                "Mainland China Bilibili",
	"game.server.global":                  "Global",
	"game.server.unknown":                 "Unknown",
	"game.status.selectFirst":             "Select and finish scanning a game installation first",
	"game.status.scanCanceled":            "Scan canceled",
	"game.status.selectGame":              "Select a game first",
	"game.status.shortcutFailed":          "Shortcut creation failed: %s",
	"game.status.shortcutCreated":         "Created: %s",
	"game.status.scanning":                "Scanning local game installations read-only…",
	"game.status.validating":              "Validating candidate paths…",
	"game.status.multiple":                "Found %d installations; select the game EXE manually",
	"game.status.notFound":                "No valid game installation was found",
	"game.status.calculating":             "Calculating directory size (cancelable)…",
	"game.status.complete":                "Read-only scan complete",
	"game.status.savePathFailed":          "Failed to save game path: %s",
	"game.status.launchInvalid":           "Invalid launch settings: %s",
	"game.status.saveLaunchFailed":        "Failed to save launch settings: %s",
	"game.customArgumentsCue":             "Custom launch arguments (optional, for example -force-d3d11)",
	"game.shortcut.name":                  "Genshin Impact - Genshin Tools",
	"resource.check":                      "Check online resources and build repair plan",
	"resource.cancel":                     "Cancel current resource task",
	"resource.voice":                      "Voice pack: %s    Click to change",
	"resource.branch":                     "Resource branch: %s    Click to change",
	"resource.branch.current":             "Current release",
	"resource.branch.preload":             "Pre-download release (when officially available)",
	"resource.apply.needPlan":             "Download and repair (build a plan first)",
	"resource.apply.count":                "Download and repair %d files",
	"resource.apply.confirm":              "Click again to confirm; original files are backed up transactionally",
	"resource.onlineVersion":              "Online version: %s",
	"resource.planSummary":                "Manifest %d files · process %d · download %s",
	"resource.progress":                   "%d/%d files · %s/%s · %s/s · remaining %s",
	"resource.eta.calculating":            "calculating",
	"resource.safety":                     "Safety boundary: downloads only enter data/staging; a short commit starts after complete verification.",
	"resource.status.ready":               "Check online resources first to build a read-only repair plan",
	"resource.status.recoveryFailed":      "A resource transaction could not be recovered automatically; check the log",
	"resource.status.canceling":           "Canceling resource task…",
	"resource.status.voiceChanged":        "Voice pack changed; check resources again",
	"resource.status.branchChanged":       "Resource branch changed; check again",
	"resource.status.noChanges":           "All current files passed verification; no repair is needed",
	"resource.status.confirm":             "Click again to confirm download and transactional replacement",
	"resource.status.reading":             "Reading the official resource catalog…",
	"resource.status.manifest":            "Verifying online manifest…",
	"resource.status.planning":            "Building a read-only repair plan file by file…",
	"resource.status.canceled":            "Resource check canceled",
	"resource.status.failed":              "Resource check failed; game files were not modified",
	"resource.status.planComplete":        "Plan complete: %d files need download or repair",
	"resource.status.preparing":           "Preparing isolated transaction…",
	"resource.status.downloading":         "Downloading to data/staging; game files remain unchanged",
	"resource.status.preloadFailed":       "Could not save pre-download; game files were not modified",
	"resource.status.preloaded":           "Pre-download fully verified in data/staging; game files were not modified",
	"resource.status.committing":          "Download fully verified; committing transaction…",
	"resource.status.taskCanceled":        "Resource task canceled; game files were not modified",
	"resource.status.txFailed":            "Resource transaction failed; original files were preserved or restored",
	"resource.status.complete":            "Resource transaction complete; all target files were verified again",
	"resource.error.needPlan":             "Build a repair plan first",
	"resource.error.gameRunning":          "Resources cannot be replaced while the game is running; exit the game first",
	"resource.error.selectGame":           "Select a game directory on the Game page first",
	"resource.error.noPreload":            "The official pre-download branch is not currently available",
	"server.mode":                         "Method: %s    Click to change",
	"server.mode.quick":                   "Official/Bilibili quick switch",
	"server.mode.advanced":                "Mainland China/Global advanced conversion",
	"server.target":                       "Target: %s    Click to change",
	"server.target.official":              "Mainland China official",
	"server.target.bilibili":              "Mainland China Bilibili",
	"server.target.global":                "Global",
	"server.plan":                         "Build change preview",
	"server.cancel":                       "Cancel current server task",
	"server.commit.inProgress":            "Transactional commit in progress (cannot be canceled safely)",
	"server.commit.needPlan":              "Commit switch (build a preview first)",
	"server.commit.count":                 "Commit %d changes",
	"server.commit.confirm":               "Click again to confirm transactional commit",
	"server.planSummary":                  "Install/replace %d · rename %d · reversible delete %d · download %s",
	"server.advancedInfo":                 "Advanced conversion verifies and downloads target differences before committing directory/EXE renames, replacements and configuration together.",
	"server.rollbackInfo":                 "The complete Plugins directory is never cleared; any failure restores the original server layout from the reverse journal.",
	"server.status.ready":                 "Build a server change preview first; the game directory will not be modified immediately",
	"server.status.canceling":             "Canceling server task…",
	"server.status.modeChanged":           "Switch method changed; rebuild the change preview",
	"server.status.targetChanged":         "Target changed; rebuild the change preview",
	"server.status.confirm":               "Click again to confirm; every replacement and deletion has a transactional backup",
	"server.status.readingQuick":          "Reading official channel SDK metadata and preparing isolated files…",
	"server.status.readingAdvanced":       "Reading target-region Sophon metadata and preparing the full difference; download may take some time…",
	"server.status.previewCanceled":       "Server preview canceled; game files were not modified",
	"server.status.previewFailed":         "Server preview failed; game files were not modified",
	"server.status.previewComplete":       "Preview complete: %d planned changes; the game directory remains unchanged until confirmation",
	"server.status.committing":            "Committing server transaction; failures roll back in reverse order…",
	"server.status.commitFailed":          "Server switch failed; original configuration and SDK were restored",
	"server.status.complete":              "Server switch complete",
	"server.error.needPreview":            "Build a server change preview first",
	"server.error.gameRunning":            "The server cannot be switched while the game is running",
	"server.error.selectGame":             "Select a valid game directory on the Game page first",
	"server.error.quickMainlandOnly":      "Official/Bilibili quick switch only supports a recognized Mainland China YuanShen.exe installation",
	"local.hdrState":                      "HDR forced state: %s    Click to change target",
	"local.brightness":                    "Brightness: peak %d · scene %d · UI %d    Click to change safe preset",
	"local.hdrApply":                      "Apply HDR (back up first, then write)",
	"local.hdrRestore":                    "Restore the previous original HDR registry values",
	"local.sound.select":                  "Select and preview WAV: %s",
	"local.sound.enabled":                 "Startup sound: %s",
	"local.betterGI.enabled":              "BetterGI protocol integration: %s",
	"local.betterGI.delay":                "BetterGI launch delay: %.1f seconds    Click to change",
	"local.betterGI.audit":                "Audit and test BetterGI URL Scheme (never terminates processes by name)",
	"local.safety":                        "Failures on this page never block a clean game launch",
	"local.sound.prompt":                  "Select startup WAV sound",
	"local.status.saveFailed":             "Failed to save local enhancement settings: %s",
	"local.status.hdrTargetChanged":       "HDR target state changed; click Apply HDR to write it",
	"local.status.hdrPresetChanged":       "HDR brightness preset changed; registry has not been modified",
	"local.status.hdrMainlandOnly":        "HDR registry adaptation only supports a recognized Mainland China game directory",
	"local.status.hdrApplyFailed":         "Failed to apply HDR; old values were preserved or restored: %s",
	"local.status.hdrApplied":             "HDR applied; original registry values were backed up",
	"local.status.hdrRestoreFailed":       "Failed to restore HDR backup: %s",
	"local.status.hdrRestored":            "Original HDR registry values restored",
	"local.status.soundSelectFailed":      "Failed to select WAV: %s",
	"local.status.soundPreviewFailed":     "Failed to preview WAV: %s",
	"local.status.soundSelected":          "Startup sound selected and previewed",
	"local.status.soundEnabled":           "Startup sound: %s",
	"local.status.betterGIEnabled":        "BetterGI integration: %s",
	"local.status.betterGIDelay":          "BetterGI delay updated",
	"local.status.betterGIAuditFailed":    "BetterGI audit failed: %s",
	"local.status.betterGINotFound":       "BetterGI URL Scheme was not found; clean launch is unaffected",
	"local.status.betterGIStartFailed":    "BetterGI test launch failed: %s",
	"local.status.betterGIStarted":        "Launch request sent to the verified BetterGI URL Scheme",
	"media.capture":                       "Game-window capture: %s    Click to change",
	"media.hotkey":                        "Global capture key: %s    Click to change safe preset",
	"media.captureNow":                    "Capture the verified game window now",
	"media.saveDir":                       "Save directory: %s",
	"media.overlay":                       "Performance overlay: %s    Click to change",
	"media.metrics":                       "Displayed metrics: %s    Click to change combination",
	"media.offset":                        "Overlay offset: X %d · Y %d    Click to change preset",
	"media.realtime":                      "Live: FPS %s · CPU %s · GPU %s",
	"media.folder.prompt":                 "Select screenshot save directory",
	"media.status.captureDisabled":        "Screenshot capture is disabled",
	"media.status.captureFailed":          "Screenshot failed: %s",
	"media.status.captureSaved":           "Screenshot saved: %s",
	"media.status.hotkeyFailed":           "Could not register screenshot hotkey: %s",
	"media.status.captureWaiting":         "Screenshot capture enabled; waiting for a verified game window",
	"media.status.captureEnabled":         "Screenshot capture enabled: %s",
	"media.status.captureStopped":         "Screenshot capture disabled",
	"media.status.hotkeyChangeFailed":     "Could not change screenshot key: %s",
	"media.status.hotkeyChanged":          "Screenshot key changed to %s",
	"media.status.requestQueued":          "Screenshot request entered the bounded queue…",
	"media.status.requestRejected":        "Could not capture: enable capture and start a verified game window",
	"media.status.folderFailed":           "Could not select screenshot directory: %s",
	"media.status.folderInvalid":          "Screenshot directory is invalid: %s",
	"media.status.folderSet":              "Screenshot directory set: %s",
	"media.status.saveFailed":             "Failed to save capture and overlay settings: %s",
	"media.status.overlayDisabled":        "Performance overlay is disabled",
	"media.status.overlayFailed":          "Overlay failed to start: %s",
	"media.status.overlayRunning":         "Overlay running: PID %d",
	"media.status.overlayStopped":         "Performance overlay stopped",
	"media.status.overlayWaiting":         "Overlay enabled; waiting for a verified game window",
	"media.status.overlayReconciling":     "Coordinating overlay lifecycle…",
	"media.error.hotkeyConflict":          "Screenshot key conflicts with an input-enhancement physical key",
	"injection.enabled":                   "Injection adaptation: %s    Disabled by default; click to change",
	"injection.risk":                      "Risk acknowledgment: %s    May trigger anti-cheat, crashes, or account risk",
	"injection.risk.confirmed":            "Acknowledged",
	"injection.risk.unconfirmed":          "Not acknowledged",
	"injection.module.none":               "No compatible module",
	"injection.module":                    "Module: %s    Click to change",
	"injection.audit":                     "Re-audit data\\injection\\modules (never downloads from the internet)",
	"injection.helper.admin":              "administrator",
	"injection.helper.current":            "current-user",
	"injection.launch":                    "Launch with isolated %s helper injection",
	"injection.cleanLaunch":               "Launch cleanly now (identical clean-launch path)",
	"injection.timeout":                   "Timeout: helper %.0f s · remote load %.0f s    Click to change",
	"injection.warning.none":              "No module audit warning",
	"injection.status.ready":              "Injection is disabled by default; clean launch is always available",
	"injection.status.invalid":            "Invalid injection settings: %s",
	"injection.status.saveFailed":         "Failed to save injection settings: %s",
	"injection.status.launchSuccess":      "Injection launch succeeded: PID %d; helper verified all modules",
	"injection.status.auditNeedGame":      "Finish game path and version scanning on the Game page first",
	"injection.status.auditing":           "Verifying module manifests, PE files, versions, and SHA-256 in the background…",
	"injection.status.auditFailed":        "Module audit failed: %s",
	"injection.status.auditComplete":      "Audit complete: %d compatible modules, %d rejected/warnings",
	"injection.status.launchNeedGame":     "Finish game scanning and launch-setting validation first",
	"injection.status.launchConfigFailed": "Could not save launch settings: %s",
	"injection.status.safeModeBlocked":    "Plugin safe mode blocked injection launch; explicitly disable safe mode on the Plugins page",
	"injection.status.rejected":           "Injection launch rejected: enable injection, acknowledge risk, and select a compatible module",
	"injection.status.starting":           "Repeating preflight checks and starting in an isolated helper…",
	"injection.status.helperDone":         "Helper completed; launcher is taking over game-process observation",
	"injection.status.launchFailed":       "Injection launch failed: %s; clean launch remains immediately available",
	"injection.status.moduleSelected":     "Selected module: %s",
	"injection.status.cleanNeedGame":      "Finish game scanning first",
	"injection.status.cleanFailed":        "Clean launch failed: %s",
	"injection.status.cleanStarted":       "Started through the clean-launch path",
	"injection.status.timeoutChanged":     "Injection timeouts updated",
	"plugin.safe":                         "Plugin safe mode: %s    Click to change",
	"plugin.safe.on":                      "On (plugin injection blocked)",
	"plugin.safe.off":                     "Off (enabled plugins may inject)",
	"plugin.rescan":                       "Rescan local plugins (offline)",
	"plugin.current":                      "Current plugin: %s    Click to change",
	"plugin.noneInstalled":                "No installed plugin",
	"plugin.enabled":                      "Enabled state: %s    Click to change",
	"plugin.aliasHint":                    "Enter a plugin alias above (empty restores the original name)",
	"plugin.aliasSave":                    "Save alias",
	"plugin.moveUp":                       "Move earlier",
	"plugin.moveDown":                     "Move later",
	"plugin.installLocal":                 "Install or update plugin from local ZIP",
	"plugin.busy":                         "Plugin audit/install in progress…",
	"plugin.rollback":                     "Roll back previous version",
	"plugin.uninstall":                    "Uninstall (confirm twice)",
	"plugin.nextPreset":                   "Next configuration preset",
	"plugin.storeCount":                   "Store %d items",
	"plugin.package.prompt":               "Select local plugin ZIP package",
	"plugin.status.invalid":               "Invalid plugin settings: %s",
	"plugin.status.saveFailed":            "Failed to save plugin settings: %s",
	"plugin.status.discoverFailed":        "Plugin discovery failed: %s",
	"plugin.status.discovered":            "Discovered %d plugins with %d warnings",
	"plugin.status.initialDiscovered":     "Discovered %d local plugins; catalog source is disabled by default",
	"plugin.status.cacheLoaded":           "Loaded catalog cache: %d items; rescan to synchronize online",
	"plugin.status.cacheInvalid":          "Plugin catalog cache is invalid; local plugins are unaffected",
	"plugin.status.stateRecovered":        "Damaged plugin state quarantined; safe defaults restored",
	"plugin.status.safeOn":                "Safe mode enabled: plugins will not be injected",
	"plugin.status.safeOff":               "Safe mode disabled: enabled plugins may inject in order",
	"plugin.status.noneInstalled":         "No installed plugin",
	"plugin.status.selected":              "Selected: %s",
	"plugin.status.selectFirst":           "Select a plugin first",
	"plugin.status.toggleFailed":          "Failed to change plugin state: %s",
	"plugin.status.stateSaveFailed":       "Failed to save plugin state: %s",
	"plugin.status.aliasInvalid":          "Invalid plugin alias: %s",
	"plugin.status.aliasSaveFailed":       "Failed to save plugin alias: %s",
	"plugin.status.aliasSaved":            "Plugin alias saved",
	"plugin.status.taskBusy":              "Another plugin task is running",
	"plugin.status.needGame":              "Finish game path and version scanning on the Game page first",
	"plugin.status.packageSelectFailed":   "Failed to select plugin package: %s",
	"plugin.status.auditingPackage":       "Auditing local plugin package in isolation; active plugins remain unchanged until completion",
	"plugin.status.packageReadFailed":     "Failed to read plugin package: %s",
	"plugin.status.installFailed":         "Plugin installation failed: %s",
	"plugin.status.installed":             "Plugin installed: %s %s",
	"plugin.status.rollbackRetained":      "; previous version retained for rollback",
	"plugin.status.rollbackNeedPlugin":    "Select a plugin and finish game scanning first",
	"plugin.status.noRollback":            "Current plugin has no rollback version",
	"plugin.status.rollingBack":           "Re-auditing and rolling back to %s",
	"plugin.status.rollbackFailed":        "Plugin rollback failed: %s",
	"plugin.status.rolledBack":            "Plugin rolled back to %s",
	"plugin.status.uninstallConfirm":      "Click uninstall again to delete this plugin and its rollback versions",
	"plugin.status.uninstalling":          "Uninstalling plugin transactionally",
	"plugin.status.uninstallFailed":       "Plugin uninstall failed: %s",
	"plugin.status.uninstalled":           "Plugin safely uninstalled: %s",
	"plugin.status.noPreset":              "Current plugin has no declarative configuration or preset",
	"plugin.status.presetUnavailable":     "Plugin configuration presets are unavailable",
	"plugin.status.configReadFailed":      "Failed to read plugin configuration: %s",
	"plugin.status.presetFailed":          "Failed to apply plugin preset: %s",
	"plugin.status.presetApplied":         "Applied configuration preset: %s",
	"plugin.status.configRecovered":       "; damaged configuration quarantined",
	"plugin.status.moveFailed":            "Could not change plugin order: %s",
	"plugin.status.orderSaveFailed":       "Failed to save plugin order: %s",
	"plugin.aliasCue":                     "Plugin alias (empty restores original name)",
	"plugin.store.catalogCue":             "FufuLauncher official plugin store",
	"plugin.store.tokenCue":               "Paste dl_token or the complete verification JSON (not saved)",
	"fufu.target.label":                   "Configuration target: %s",
	"fufu.target.selector":                "Configuration target: FuFuPlugin (main)  |  %s",
	"fufu.target.notInstalled":            "FuFuPlugin is not installed",
	"fufu.target.repair":                  "Download / Repair",
	"fufu.target.injection":               "Injection: %s",
	"fufu.target.openConfig":              "FuFuPlugin configuration >",
	"fufu.target.openGeneric":             "Open generic plugin management",
	"fufu.status.saveFailed":              "Could not save FuFuPlugin setting: %v",
	"fufu.status.configReadFailed":        "Could not read FuFuPlugin settings: %v",
	"fufu.status.controlFailed":           "Could not create the editor for %s: %v",
	"fufu.status.saved":                   "Saved FuFuPlugin setting: %s",
	"fufu.setting.scroll":                 "Showing %d-%d of %d; use the mouse wheel to scroll",
	"fufu.status.downloading":             "Downloading FuFuPlugin from Fufu's official GitHub path...",
	"fufu.status.repairFailed":            "FuFuPlugin download/repair failed: %v",
	"fufu.status.repaired":                "FuFuPlugin %s installed and audited (package SHA-256 %s...)",
	"fufu.status.notInstalled":            "FuFuPlugin is not installed; run Download/Repair first",
	"fufu.status.toggleFailed":            "Could not change FuFuPlugin injection state: %v",
	"fufu.status.toggled":                 "FuFuPlugin injection is now %s",
	"plugin.store.searchCue":              "Search plugin name, developer, description or tags",
	"plugin.store.sync":                   "Synchronize FufuLauncher plugin store",
	"plugin.store.sourceFufu":             "Source: FufuLauncher official store (fu1.fun)",
	"plugin.store.busy":                   "Plugin catalog or installation task in progress…",
	"plugin.store.none":                   "No plugin on the current page",
	"plugin.store.install":                "Verify / securely install selected Fufu plugin",
	"plugin.store.repair":                 "Re-download, re-audit and repair selected plugin",
	"plugin.store.update":                 "Download, re-audit and update selected plugin",
	"plugin.store.installed":              "Installed",
	"plugin.store.versionDiff":            "Installed %s, catalog %s",
	"plugin.store.selected":               "Store plugin: %s    Click to change",
	"plugin.store.category":               "Category: %s    Click to change",
	"plugin.store.category.all":           "All",
	"plugin.store.category.utility":       "Utility",
	"plugin.store.category.gameplay":      "Gameplay",
	"plugin.store.category.visuals":       "Visuals",
	"plugin.store.category.other":         "Other",
	"plugin.store.sort":                   "Sort: %s    Click to change",
	"plugin.store.sort.popular":           "Popular",
	"plugin.store.sort.newest":            "Newest",
	"plugin.store.sort.rating":            "Rating",
	"plugin.store.sort.name":              "Name",
	"plugin.store.previous":               "Previous page",
	"plugin.store.next":                   "Next page    %d/%d",
	"plugin.store.status.syncing":         "Synchronizing and validating plugin catalog",
	"plugin.store.status.syncFailed":      "Plugin catalog synchronization failed; previous cache retained: %s",
	"plugin.store.status.queryFailed":     "Plugin catalog query failed: %s",
	"plugin.store.status.synced":          "Catalog synchronized: %d items, page %d/%d",
	"plugin.store.status.filterInvalid":   "Invalid plugin store filter: %s",
	"plugin.store.status.filterFailed":    "Failed to filter plugin catalog: %s",
	"plugin.store.status.saveFailed":      "Failed to save plugin store settings: %s",
	"plugin.store.status.filterUpdated":   "Store filters updated: %d items",
	"plugin.store.status.empty":           "No store plugin matches the current filters",
	"plugin.store.status.selected":        "Store selection: %s",
	"plugin.store.status.busyNeedGame":    "Wait for the current task and finish game scanning first",
	"plugin.store.status.selectFirst":     "Synchronize and select a store plugin first",
	"plugin.store.status.downloading":     "Downloading, validating and installing %s in isolation",
	"plugin.store.status.stagingFailed":   "Failed to create plugin download staging file: %s",
	"plugin.store.status.downloadFailed":  "Plugin download failed: %s",
	"plugin.store.status.installFailed":   "Store plugin installation failed: %s",
	"plugin.store.status.installed":       "Store plugin installed: %s %s",
	"plugin.store.status.openedFufu":      "Opened Fufu official verification page for %s in the system browser",
	"plugin.store.status.openFufuFailed":  "Failed to open Fufu official verification page: %s",
	"plugin.store.status.needToken":       "Opened Fufu verification for %s; complete it, then paste dl_token or the complete JSON above and click again",
	"plugin.store.status.tokenInvalid":    "Invalid Fufu download token: %s",
	"plugin.store.status.needGame":        "Scan and select the current game installation before installing a Fufu plugin",
	"settings.subtitle":                   "Language, appearance, tray, window, diagnostics and version information.",
	"settings.language":                   "Language",
	"settings.language.system":            "System default",
	"settings.language.zh":                "Simplified Chinese",
	"settings.language.en":                "English",
	"settings.theme":                      "Theme",
	"settings.theme.dark":                 "Dark",
	"settings.theme.system":               "Follow Windows",
	"settings.tray":                       "Minimize to notification area",
	"settings.rememberWindow":             "Remember window position and size",
	"settings.minimumSize":                "Enforce safe minimum window size",
	"settings.priority":                   "Process priority",
	"settings.priority.below":             "Below normal",
	"settings.priority.normal":            "Normal",
	"settings.priority.above":             "Above normal",
	"settings.cpuWarning":                 "Warn when launcher CPU usage stays high",
	"settings.cpuWarning.title":           "High launcher CPU usage",
	"settings.cpuWarning.message":         "Launcher CPU usage remained above the configured threshold.",
	"settings.cpuWarning.summary":         "%s: %s · %d%% / %.0fs",
	"settings.about":                      "About and build identity",
	"settings.diagnostics":                "Export privacy-filtered diagnostics",
	"settings.upstream":                   "Audited upstream commit",
	"settings.scope":                      "Scope policy",
	"settings.status.saved":               "Settings saved",
	"settings.status.ready":               "Settings are ready",
	"settings.status.saveFailed":          "Failed to save settings: ",
	"settings.status.priorityFailed":      "Failed to apply process priority: %s",
	"settings.status.exporting":           "Exporting diagnostics…",
	"settings.status.exported":            "Diagnostics exported: ",
	"settings.status.exportFailed":        "Failed to export diagnostics: ",
	"settings.diagnostics.prompt":         "Select diagnostic export folder",
}

var zhCN = map[string]string{
	"app.title":                           "Genshin Tools",
	"nav.home":                            "首页",
	"nav.game":                            "游戏管理",
	"nav.resources":                       "资源管理",
	"nav.server":                          "区服工具",
	"nav.local":                           "本地增强",
	"nav.capture":                         "截图与性能",
	"nav.input":                           "输入增强",
	"nav.injection":                       "注入适配",
	"nav.plugins":                         "插件",
	"nav.pluginStore":                     "插件商店",
	"nav.settings":                        "设置",
	"nav.home.subtitle":                   "启动状态与常用操作。",
	"nav.game.subtitle":                   "只读状态、纯净启动和启动设置。",
	"nav.resources.subtitle":              "检查、下载并事务修复游戏资源。",
	"nav.server.subtitle":                 "官服/B服切换与高级转换。",
	"nav.local.subtitle":                  "HDR、启动声音、BetterGI 与可回滚本地操作。",
	"nav.capture.subtitle":                "游戏窗口截图与 FPS/CPU/GPU 覆盖层。",
	"nav.input.subtitle":                  "鼠标连点与键盘连按。",
	"nav.injection.subtitle":              "独立 helper、模块预检和纯净启动回退。",
	"nav.plugins.subtitle":                "插件发现、配置、来源审计和更新。",
	"nav.pluginStore.subtitle":            "FufuLauncher 插件商店、筛选与官方验证流程。",
	"nav.settings.subtitle":               "语言、外观、托盘、诊断与构建身份。",
	"status.previousUncleanExit":          "已检测到上次异常退出。",
	"status.configRecovered":              "已隔离损坏配置。",
	"common.on":                           "开启",
	"common.off":                          "关闭",
	"common.enable":                       "启用",
	"common.disable":                      "禁用",
	"common.unknown":                      "未知",
	"common.label":                        "%s：%s",
	"home.ready":                          "启动器服务已就绪",
	"home.summary":                        "单实例 · 通知区域 · 每显示器 DPI · 原子配置 · 安全退出",
	"home.scope":                          "仅保留启动器功能；不包含账号、米游社/BBS、工具箱和浏览器功能。",
	"input.toggle":                        "输入增强：%s    单击%s",
	"input.mode.keyboard":                 "键盘连按",
	"input.mode.mouseLeft":                "左键连点",
	"input.mode.mouseRight":               "右键连点",
	"input.key.trigger":                   "触发键",
	"input.key.output":                    "输出键",
	"input.key.stop":                      "全局停止键",
	"input.mouseTrigger":                  "触发方式：按住对应物理鼠标键",
	"input.interval":                      "−       间隔 %d ms       +",
	"input.error":                         "错误：%s",
	"input.outputCount":                   "已输出 %d 组完整 down/up；重启后默认保持禁用",
	"input.record.pending":                "%s：请按下新按键…",
	"input.record.ready":                  "%s：%s    单击录制",
	"input.state.disabled":                "已禁用",
	"input.state.armed":                   "待触发",
	"input.state.running":                 "运行中",
	"input.state.stopping":                "停止中",
	"input.state.fault":                   "故障",
	"input.state.unknown":                 "未知",
	"input.error.captureConflict":         "该物理键已被截图快捷键使用；即使修饰键不同也可能触发输入停止逻辑",
	"game.launch.clean":                   "纯净启动游戏",
	"game.launch.starting":                "正在启动…",
	"game.launch.running":                 "游戏运行中（本次 PID %d）",
	"game.windowMode":                     "窗口模式：%s    单击切换",
	"game.window.default":                 "游戏默认",
	"game.window.fullscreen":              "全屏",
	"game.window.windowed":                "窗口",
	"game.window.borderless":              "无边框",
	"game.resolution":                     "分辨率：%s    单击切换预设",
	"game.monitor.default":                "默认",
	"game.monitor.number":                 "显示器 %d",
	"game.target":                         "目标：%s",
	"game.after":                          "之后：%s",
	"game.post.keep":                      "保持启动器",
	"game.post.minimize":                  "最小化到托盘",
	"game.post.exit":                      "启动后退出",
	"game.action.scan":                    "重新扫描/取消",
	"game.action.select":                  "选择游戏 EXE",
	"game.action.shortcut":                "创建桌面快捷方式",
	"game.error.launch":                   "启动错误：%s",
	"game.error.process":                  "游戏进程错误：%s",
	"game.exited":                         "游戏已退出，代码 %d；启动器可再次启动",
	"game.path":                           "路径：%s",
	"game.identity":                       "%s    版本 %s    %s",
	"game.files":                          "%s · %d 文件 · 跳过 %d · %s",
	"game.running.none":                   "未运行",
	"game.running.verified":               "运行中 PID %d（路径已核验）",
	"game.running.possible":               "可能运行 PID %d（仅名称匹配）",
	"game.server.official":                "国服官服",
	"game.server.bilibili":                "国服 B 服",
	"game.server.global":                  "国际服",
	"game.server.unknown":                 "未知",
	"game.status.selectFirst":             "请先选择并完成游戏扫描",
	"game.status.scanCanceled":            "扫描已取消",
	"game.status.selectGame":              "请先选择游戏",
	"game.status.shortcutFailed":          "快捷方式失败：%s",
	"game.status.shortcutCreated":         "已创建：%s",
	"game.status.scanning":                "正在只读扫描本机游戏…",
	"game.status.validating":              "正在验证候选路径…",
	"game.status.multiple":                "发现 %d 个安装，请手动选择游戏 EXE",
	"game.status.notFound":                "未找到有效游戏安装",
	"game.status.calculating":             "正在计算目录大小（可取消）…",
	"game.status.complete":                "只读扫描完成",
	"game.status.savePathFailed":          "保存游戏路径：%s",
	"game.status.launchInvalid":           "启动设置无效：%s",
	"game.status.saveLaunchFailed":        "保存启动设置失败：%s",
	"game.customArgumentsCue":             "自定义启动参数（可留空，例如 -force-d3d11）",
	"game.shortcut.name":                  "原神 - Genshin Tools",
	"resource.check":                      "检查在线资源并生成修复计划",
	"resource.cancel":                     "取消当前资源任务",
	"resource.voice":                      "语音包：%s    单击切换",
	"resource.branch":                     "资源分支：%s    单击切换",
	"resource.branch.current":             "当前正式版本",
	"resource.branch.preload":             "预下载版本（仅官方开放时可用）",
	"resource.apply.needPlan":             "下载并修复（需要先生成计划）",
	"resource.apply.count":                "下载并修复 %d 个文件",
	"resource.apply.confirm":              "再次单击确认执行；原文件将在事务中备份",
	"resource.onlineVersion":              "在线版本：%s",
	"resource.planSummary":                "清单 %d 个文件 · 需处理 %d 个 · 下载量 %s",
	"resource.progress":                   "%d/%d 文件 · %s/%s · %s/s · 剩余 %s",
	"resource.eta.calculating":            "计算中",
	"resource.safety":                     "安全边界：下载仅写入 data/staging；完整校验后才进入短暂提交阶段。",
	"resource.status.ready":               "先检查在线资源并生成只读修复计划",
	"resource.status.recoveryFailed":      "检测到未能自动恢复的资源事务，请查看日志",
	"resource.status.canceling":           "正在取消资源任务…",
	"resource.status.voiceChanged":        "语音包已切换，请重新检查资源",
	"resource.status.branchChanged":       "资源分支已切换，请重新检查",
	"resource.status.noChanges":           "当前文件均已通过校验，无需修复",
	"resource.status.confirm":             "再次单击以确认下载并事务替换列出的文件",
	"resource.status.reading":             "正在读取官方资源目录…",
	"resource.status.manifest":            "正在校验在线 manifest…",
	"resource.status.planning":            "正在逐文件生成只读修复计划…",
	"resource.status.canceled":            "资源检查已取消",
	"resource.status.failed":              "资源检查失败，未修改游戏文件",
	"resource.status.planComplete":        "计划完成：%d 个文件需下载或修复",
	"resource.status.preparing":           "正在准备隔离事务…",
	"resource.status.downloading":         "正在下载到 data/staging；正式文件保持不变",
	"resource.status.preloadFailed":       "预下载保存失败；正式文件未修改",
	"resource.status.preloaded":           "预下载已完整校验并保存在 data/staging；正式文件未修改",
	"resource.status.committing":          "下载已完整校验，正在提交事务…",
	"resource.status.taskCanceled":        "资源任务已取消；正式文件未修改",
	"resource.status.txFailed":            "资源事务失败；已保留或恢复原文件",
	"resource.status.complete":            "资源事务完成，全部目标文件已再次校验",
	"resource.error.needPlan":             "请先生成修复计划",
	"resource.error.gameRunning":          "游戏运行时不能替换资源，请先退出游戏",
	"resource.error.selectGame":           "请先在游戏管理页选择游戏目录",
	"resource.error.noPreload":            "官方当前没有开放预下载分支",
	"server.mode":                         "方式：%s    单击切换",
	"server.mode.quick":                   "官服/B服快速切换",
	"server.mode.advanced":                "国服/国际服高级转换",
	"server.target":                       "目标：%s    单击切换",
	"server.target.official":              "国服官服",
	"server.target.bilibili":              "国服 B 服",
	"server.target.global":                "国际服",
	"server.plan":                         "生成变更预览",
	"server.cancel":                       "取消当前区服任务",
	"server.commit.inProgress":            "区服事务提交中（不能安全取消）",
	"server.commit.needPlan":              "提交切换（需要先生成预览）",
	"server.commit.count":                 "提交 %d 项变更",
	"server.commit.confirm":               "再次单击确认事务提交",
	"server.planSummary":                  "安装/替换 %d · 改名 %d · 可回滚删除 %d · 下载 %s",
	"server.advancedInfo":                 "高级转换会先校验并下载目标差异，再统一提交目录/EXE 改名、替换和配置。",
	"server.rollbackInfo":                 "不会清空整个 Plugins；任一步失败均按反向日志恢复原区服布局。",
	"server.status.ready":                 "先生成区服变更预览；不会直接修改游戏目录",
	"server.status.canceling":             "正在取消区服任务…",
	"server.status.modeChanged":           "切换方式已更改，请重新生成变更预览",
	"server.status.targetChanged":         "目标已切换，请重新生成变更预览",
	"server.status.confirm":               "再次单击确认提交；所有替换和删除均有事务备份",
	"server.status.readingQuick":          "正在读取官方渠道 SDK 清单并准备隔离文件…",
	"server.status.readingAdvanced":       "正在读取目标区服 Sophon 清单并准备完整差异；可能需要较长下载…",
	"server.status.previewCanceled":       "区服预览已取消；游戏文件未修改",
	"server.status.previewFailed":         "区服预览失败；游戏文件未修改",
	"server.status.previewComplete":       "预览完成：%d 项计划，确认前不会修改游戏目录",
	"server.status.committing":            "正在提交区服事务；失败将自动逆序回滚…",
	"server.status.commitFailed":          "区服切换失败；原配置和 SDK 已恢复",
	"server.status.complete":              "区服切换完成",
	"server.error.needPreview":            "请先生成区服变更预览",
	"server.error.gameRunning":            "游戏运行时不能切换区服",
	"server.error.selectGame":             "请先在游戏管理页选择有效游戏目录",
	"server.error.quickMainlandOnly":      "官服/B服快速切换仅适用于已识别的国服 YuanShen.exe",
	"local.hdrState":                      "HDR 强制状态：%s    单击切换目标",
	"local.brightness":                    "亮度：峰值 %d · 场景 %d · UI %d    单击切换安全预设",
	"local.hdrApply":                      "应用 HDR（先备份，再写入）",
	"local.hdrRestore":                    "恢复上一次 HDR 原始注册表值",
	"local.sound.select":                  "选择并试听 WAV：%s",
	"local.sound.enabled":                 "启动声音：%s",
	"local.betterGI.enabled":              "BetterGI 协议联动：%s",
	"local.betterGI.delay":                "BetterGI 启动延迟：%.1f 秒    单击切换",
	"local.betterGI.audit":                "审计并测试 BetterGI URL Scheme（不会按名称结束进程）",
	"local.safety":                        "本页操作失败不会阻止纯净游戏启动",
	"local.sound.prompt":                  "选择启动声音 WAV",
	"local.status.saveFailed":             "保存本地增强设置失败：%s",
	"local.status.hdrTargetChanged":       "HDR 目标状态已更改；单击“应用 HDR”后写入",
	"local.status.hdrPresetChanged":       "HDR 亮度预设已更改，尚未写入注册表",
	"local.status.hdrMainlandOnly":        "HDR 注册表适配仅用于已识别的国服目录",
	"local.status.hdrApplyFailed":         "应用 HDR 失败，旧值已保留或恢复：%s",
	"local.status.hdrApplied":             "HDR 已应用；原始注册表值已备份",
	"local.status.hdrRestoreFailed":       "恢复 HDR 备份失败：%s",
	"local.status.hdrRestored":            "HDR 原始注册表值已恢复",
	"local.status.soundSelectFailed":      "选择 WAV 失败：%s",
	"local.status.soundPreviewFailed":     "WAV 试听失败：%s",
	"local.status.soundSelected":          "启动声音已选择并试听",
	"local.status.soundEnabled":           "启动声音：%s",
	"local.status.betterGIEnabled":        "BetterGI 联动：%s",
	"local.status.betterGIDelay":          "BetterGI 延迟已更新",
	"local.status.betterGIAuditFailed":    "BetterGI 审计失败：%s",
	"local.status.betterGINotFound":       "未发现 BetterGI URL Scheme；不会影响纯净启动",
	"local.status.betterGIStartFailed":    "BetterGI 测试启动失败：%s",
	"local.status.betterGIStarted":        "已向核验后的 BetterGI URL Scheme 发送启动请求",
	"media.capture":                       "游戏窗口截图：%s    单击切换",
	"media.hotkey":                        "全局截图键：%s    单击切换安全预设",
	"media.captureNow":                    "立即截取已核验游戏窗口",
	"media.saveDir":                       "保存目录：%s",
	"media.overlay":                       "性能覆盖层：%s    单击切换",
	"media.metrics":                       "显示指标：%s    单击切换组合",
	"media.offset":                        "覆盖层偏移：X %d · Y %d    单击切换预设",
	"media.realtime":                      "实时：FPS %s · CPU %s · GPU %s",
	"media.folder.prompt":                 "选择截图保存目录",
	"media.status.captureDisabled":        "截图功能未启用",
	"media.status.captureFailed":          "截图失败：%s",
	"media.status.captureSaved":           "截图已保存：%s",
	"media.status.hotkeyFailed":           "截图快捷键注册失败：%s",
	"media.status.captureWaiting":         "截图已启用，等待已核验游戏窗口",
	"media.status.captureEnabled":         "截图已启用：%s",
	"media.status.captureStopped":         "截图功能已停用",
	"media.status.hotkeyChangeFailed":     "切换截图键失败：%s",
	"media.status.hotkeyChanged":          "截图键已改为 %s",
	"media.status.requestQueued":          "截图请求已进入有界队列…",
	"media.status.requestRejected":        "无法截图：请启用截图并启动已核验的游戏窗口",
	"media.status.folderFailed":           "选择截图目录失败：%s",
	"media.status.folderInvalid":          "截图目录无效：%s",
	"media.status.folderSet":              "截图目录已设置：%s",
	"media.status.saveFailed":             "保存截图与覆盖层设置失败：%s",
	"media.status.overlayDisabled":        "性能覆盖层未启用",
	"media.status.overlayFailed":          "覆盖层启动失败：%s",
	"media.status.overlayRunning":         "覆盖层运行中：PID %d",
	"media.status.overlayStopped":         "性能覆盖层已停止",
	"media.status.overlayWaiting":         "覆盖层已启用，等待已核验游戏窗口",
	"media.status.overlayReconciling":     "正在协调覆盖层生命周期…",
	"media.error.hotkeyConflict":          "截图键与输入增强物理键冲突",
	"injection.enabled":                   "注入适配：%s    默认关闭，单击切换",
	"injection.risk":                      "风险确认：%s    可能触发反作弊、崩溃或账号风险",
	"injection.risk.confirmed":            "已确认",
	"injection.risk.unconfirmed":          "未确认",
	"injection.module.none":               "无兼容模块",
	"injection.module":                    "模块：%s    单击切换",
	"injection.audit":                     "重新审计 data\\injection\\modules（不会联网下载）",
	"injection.helper.admin":              "管理员",
	"injection.helper.current":            "当前用户",
	"injection.launch":                    "使用独立%s helper 注入启动",
	"injection.cleanLaunch":               "立即纯净启动（使用完全相同的纯净启动路径）",
	"injection.timeout":                   "超时：helper %.0f 秒 · 远程加载 %.0f 秒    单击切换",
	"injection.warning.none":              "无模块审计警告",
	"injection.status.ready":              "注入默认关闭；纯净启动始终可用",
	"injection.status.invalid":            "注入设置无效：%s",
	"injection.status.saveFailed":         "保存注入设置失败：%s",
	"injection.status.launchSuccess":      "注入启动成功：PID %d；模块已由 helper 核验",
	"injection.status.auditNeedGame":      "请先在游戏管理页完成游戏路径与版本扫描",
	"injection.status.auditing":           "正在后台核验模块 manifest、PE、版本与 SHA-256…",
	"injection.status.auditFailed":        "模块审计失败：%s",
	"injection.status.auditComplete":      "审计完成：%d 个兼容模块，%d 个拒绝/警告",
	"injection.status.launchNeedGame":     "请先完成游戏扫描和启动设置校验",
	"injection.status.launchConfigFailed": "无法保存启动设置：%s",
	"injection.status.safeModeBlocked":    "注入启动被插件安全模式阻止；请在插件页明确关闭安全模式",
	"injection.status.rejected":           "注入启动被拒绝：请启用注入、确认风险并选择兼容模块",
	"injection.status.starting":           "正在独立 helper 中重复预检并启动…",
	"injection.status.helperDone":         "helper 已完成，正在接管游戏进程观察",
	"injection.status.launchFailed":       "注入启动失败：%s；可立即使用纯净启动",
	"injection.status.moduleSelected":     "已选择模块：%s",
	"injection.status.cleanNeedGame":      "请先完成游戏扫描",
	"injection.status.cleanFailed":        "纯净启动失败：%s",
	"injection.status.cleanStarted":       "已使用纯净启动路径",
	"injection.status.timeoutChanged":     "注入超时设置已更新",
	"plugin.safe":                         "插件安全模式：%s    单击切换",
	"plugin.safe.on":                      "开启（禁止插件注入）",
	"plugin.safe.off":                     "关闭（允许启用项注入）",
	"plugin.rescan":                       "重新扫描本地插件（不联网）",
	"plugin.current":                      "当前插件：%s    单击切换",
	"plugin.noneInstalled":                "无已安装插件",
	"plugin.enabled":                      "启用状态：%s    单击切换",
	"plugin.aliasHint":                    "在上方输入插件别名（留空恢复原名）",
	"plugin.aliasSave":                    "保存别名",
	"plugin.moveUp":                       "顺序向前",
	"plugin.moveDown":                     "顺序向后",
	"plugin.installLocal":                 "从本地 ZIP 安装或更新插件",
	"plugin.busy":                         "插件审计/安装进行中…",
	"plugin.rollback":                     "回滚上一版本",
	"plugin.uninstall":                    "卸载（二次确认）",
	"plugin.nextPreset":                   "下一个配置预设",
	"plugin.storeCount":                   "商店 %d 项",
	"plugin.package.prompt":               "选择本地插件 ZIP 包",
	"plugin.status.invalid":               "插件设置无效：%s",
	"plugin.status.saveFailed":            "保存插件设置失败：%s",
	"plugin.status.discoverFailed":        "发现插件失败：%s",
	"plugin.status.discovered":            "已发现 %d 个插件，%d 条警告",
	"plugin.status.initialDiscovered":     "已发现 %d 个本地插件；目录源默认关闭",
	"plugin.status.cacheLoaded":           "已载入目录缓存：%d 项；重新扫描可联网同步",
	"plugin.status.cacheInvalid":          "插件目录缓存无效，未影响本地插件",
	"plugin.status.stateRecovered":        "损坏的插件状态已隔离，已恢复安全默认值",
	"plugin.status.safeOn":                "安全模式已开启：插件不会注入",
	"plugin.status.safeOff":               "安全模式已关闭：仅启用插件会按顺序注入",
	"plugin.status.noneInstalled":         "没有已安装插件",
	"plugin.status.selected":              "已选择：%s",
	"plugin.status.selectFirst":           "请先选择插件",
	"plugin.status.toggleFailed":          "切换插件失败：%s",
	"plugin.status.stateSaveFailed":       "保存插件状态失败：%s",
	"plugin.status.aliasInvalid":          "插件别名无效：%s",
	"plugin.status.aliasSaveFailed":       "保存插件别名失败：%s",
	"plugin.status.aliasSaved":            "插件别名已保存",
	"plugin.status.taskBusy":              "已有插件任务正在执行",
	"plugin.status.needGame":              "请先在游戏管理页完成游戏路径和版本扫描",
	"plugin.status.packageSelectFailed":   "选择插件包失败：%s",
	"plugin.status.auditingPackage":       "正在隔离区审计本地插件包；完成前不会修改活动插件",
	"plugin.status.packageReadFailed":     "读取插件包失败：%s",
	"plugin.status.installFailed":         "安装插件失败：%s",
	"plugin.status.installed":             "插件已安装：%s %s",
	"plugin.status.rollbackRetained":      "；上一版本已保留用于回滚",
	"plugin.status.rollbackNeedPlugin":    "请先选择插件并完成游戏扫描",
	"plugin.status.noRollback":            "当前插件没有可回滚版本",
	"plugin.status.rollingBack":           "正在重新审计并回滚到 %s",
	"plugin.status.rollbackFailed":        "插件回滚失败：%s",
	"plugin.status.rolledBack":            "插件已回滚到 %s",
	"plugin.status.uninstallConfirm":      "再次单击卸载以确认删除该插件及其回滚版本",
	"plugin.status.uninstalling":          "正在事务化卸载插件",
	"plugin.status.uninstallFailed":       "卸载插件失败：%s",
	"plugin.status.uninstalled":           "插件已安全卸载：%s",
	"plugin.status.noPreset":              "当前插件没有声明式配置和预设",
	"plugin.status.presetUnavailable":     "插件配置预设不可用",
	"plugin.status.configReadFailed":      "读取插件配置失败：%s",
	"plugin.status.presetFailed":          "应用插件预设失败：%s",
	"plugin.status.presetApplied":         "已应用配置预设：%s",
	"plugin.status.configRecovered":       "；损坏配置已隔离",
	"plugin.status.moveFailed":            "无法调整顺序：%s",
	"plugin.status.orderSaveFailed":       "保存插件顺序失败：%s",
	"plugin.aliasCue":                     "插件别名（留空恢复原名）",
	"plugin.store.catalogCue":             "FufuLauncher 官方插件商店",
	"plugin.store.tokenCue":               "粘贴 dl_token 或完整验证 JSON（不会保存）",
	"fufu.target.label":                   "配置目标：%s",
	"fufu.target.selector":                "配置目标：FuFuPlugin（主插件）  |  %s",
	"fufu.target.notInstalled":            "FuFuPlugin 尚未安装",
	"fufu.target.repair":                  "功能（下载/修复）",
	"fufu.target.injection":               "启用注入：%s",
	"fufu.target.openConfig":              "FuFuPlugin 配置 >",
	"fufu.target.openGeneric":             "打开通用插件管理",
	"fufu.status.saveFailed":              "FuFuPlugin 设置保存失败：%v",
	"fufu.status.configReadFailed":        "FuFuPlugin 设置读取失败：%v",
	"fufu.status.controlFailed":           "无法为“%s”创建编辑控件：%v",
	"fufu.status.saved":                   "已保存 FuFuPlugin 设置：%s",
	"fufu.setting.scroll":                 "当前显示 %d-%d / 共 %d 项；使用鼠标滚轮滚动",
	"fufu.status.downloading":             "正在从 Fufu 当前官方 GitHub 路径下载 FuFuPlugin……",
	"fufu.status.repairFailed":            "FuFuPlugin 下载/修复失败：%v",
	"fufu.status.repaired":                "FuFuPlugin %s 已安装并通过审计（包 SHA-256 %s…）",
	"fufu.status.notInstalled":            "尚未安装 FuFuPlugin，请先执行下载/修复",
	"fufu.status.toggleFailed":            "FuFuPlugin 注入状态切换失败：%v",
	"fufu.status.toggled":                 "FuFuPlugin 注入现为%s",
	"plugin.store.searchCue":              "搜索插件名称、作者、描述或标签",
	"plugin.store.sync":                   "同步 FufuLauncher 插件商店",
	"plugin.store.sourceFufu":             "来源：FufuLauncher 官方商店（fu1.fun）",
	"plugin.store.busy":                   "插件目录或安装任务进行中…",
	"plugin.store.none":                   "当前页没有插件",
	"plugin.store.install":                "验证 / 安全安装所选 Fufu 插件",
	"plugin.store.repair":                 "重新下载、复核并修复所选插件",
	"plugin.store.update":                 "下载、复核并更新所选插件",
	"plugin.store.installed":              "已安装",
	"plugin.store.versionDiff":            "已安装 %s，目录版本 %s",
	"plugin.store.selected":               "商店插件：%s    单击切换",
	"plugin.store.category":               "分类：%s    单击切换",
	"plugin.store.category.all":           "全部",
	"plugin.store.category.utility":       "实用工具",
	"plugin.store.category.gameplay":      "游戏功能",
	"plugin.store.category.visuals":       "视觉",
	"plugin.store.category.other":         "其他",
	"plugin.store.sort":                   "排序：%s    单击切换",
	"plugin.store.sort.popular":           "热门",
	"plugin.store.sort.newest":            "最新",
	"plugin.store.sort.rating":            "评分",
	"plugin.store.sort.name":              "名称",
	"plugin.store.previous":               "上一页",
	"plugin.store.next":                   "下一页    %d/%d",
	"plugin.store.status.syncing":         "正在同步并校验插件目录",
	"plugin.store.status.syncFailed":      "插件目录同步失败，保留原缓存：%s",
	"plugin.store.status.queryFailed":     "插件目录查询失败：%s",
	"plugin.store.status.synced":          "目录同步完成：共 %d 项，当前第 %d/%d 页",
	"plugin.store.status.filterInvalid":   "插件商店筛选无效：%s",
	"plugin.store.status.filterFailed":    "筛选插件目录失败：%s",
	"plugin.store.status.saveFailed":      "保存插件商店设置失败：%s",
	"plugin.store.status.filterUpdated":   "商店筛选已更新：%d 项",
	"plugin.store.status.empty":           "当前筛选没有商店插件",
	"plugin.store.status.selected":        "商店已选择：%s",
	"plugin.store.status.busyNeedGame":    "请等待当前任务结束并先完成游戏扫描",
	"plugin.store.status.selectFirst":     "请先同步并选择商店插件",
	"plugin.store.status.downloading":     "正在下载、校验并隔离安装 %s",
	"plugin.store.status.stagingFailed":   "创建插件下载暂存文件失败：%s",
	"plugin.store.status.downloadFailed":  "下载插件失败：%s",
	"plugin.store.status.installFailed":   "安装商店插件失败：%s",
	"plugin.store.status.installed":       "商店插件已安装：%s %s",
	"plugin.store.status.openedFufu":      "已用系统浏览器打开 %s 的 Fufu 官方验证页",
	"plugin.store.status.openFufuFailed":  "打开 Fufu 官方验证页失败：%s",
	"plugin.store.status.needToken":       "已打开 %s 的 Fufu 验证页；完成后将 dl_token 或完整 JSON 粘贴到上方并再次单击",
	"plugin.store.status.tokenInvalid":    "Fufu 下载令牌无效：%s",
	"plugin.store.status.needGame":        "安装 Fufu 插件前请先扫描并选择当前游戏目录",
	"settings.subtitle":                   "语言、外观、托盘、窗口、诊断与版本信息。",
	"settings.language":                   "语言",
	"settings.language.system":            "跟随系统",
	"settings.language.zh":                "简体中文",
	"settings.language.en":                "English",
	"settings.theme":                      "主题",
	"settings.theme.dark":                 "暗色",
	"settings.theme.system":               "跟随 Windows",
	"settings.tray":                       "最小化到通知区域",
	"settings.rememberWindow":             "记住窗口位置和尺寸",
	"settings.minimumSize":                "启用安全最小窗口尺寸",
	"settings.priority":                   "程序进程优先级",
	"settings.priority.below":             "低于正常",
	"settings.priority.normal":            "正常",
	"settings.priority.above":             "高于正常",
	"settings.cpuWarning":                 "程序持续高 CPU 占用时提醒",
	"settings.cpuWarning.title":           "程序 CPU 占用持续偏高",
	"settings.cpuWarning.message":         "程序 CPU 占用已持续超过配置阈值。",
	"settings.cpuWarning.summary":         "%s：%s · %d%% / %.0f 秒",
	"settings.about":                      "关于与构建身份",
	"settings.diagnostics":                "导出经过隐私过滤的诊断",
	"settings.upstream":                   "已审计上游提交",
	"settings.scope":                      "范围策略",
	"settings.status.saved":               "设置已保存",
	"settings.status.ready":               "设置已就绪",
	"settings.status.saveFailed":          "保存设置失败：",
	"settings.status.priorityFailed":      "应用进程优先级失败：%s",
	"settings.status.exporting":           "正在导出诊断…",
	"settings.status.exported":            "诊断已导出：",
	"settings.status.exportFailed":        "导出诊断失败：",
	"settings.diagnostics.prompt":         "选择诊断导出目录",
}
